# Select which datastore mode. Can be 'etcd' or 'kdd'.
# Note: Changing this after installation is not supported.
datastore: kdd

# Sets the networking mode. Can be 'calico', 'flannel', or 'none'
network: "none"

# Sets the ipam. Can be 'calico-ipam' or 'host-local'
ipam: calico-ipam
app_layer_policy: false

prodname: Calico
nodecontainer: node
